"""empty message

Revision ID: 23f05225dcaf
Revises: 2ad7734ca7ba
Create Date: 2022-04-03 02:54:56.778399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f05225dcaf'
down_revision = '2ad7734ca7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('passwrd', sa.String(length=25), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_num', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=7), nullable=True),
    sa.Column('radius', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('is_retail', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=7), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('expiry', sa.String(length=15), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('category')
    # ### end Alembic commands ###
