"""empty message

Revision ID: 2ad7734ca7ba
Revises: 3209ab9ae3f5
Create Date: 2022-04-03 02:08:34.159214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad7734ca7ba'
down_revision = '3209ab9ae3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.drop_table('category')
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_category_id_fkey', 'products', 'category', ['category_id'], ['category_id'])
    op.create_table('category',
    sa.Column('category_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('category_id', name='category_pkey')
    )
    op.drop_table('categories')
    # ### end Alembic commands ###
