"""empty message

Revision ID: 3209ab9ae3f5
Revises: a209c1a3f8cf
Create Date: 2022-04-03 01:56:22.002442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3209ab9ae3f5'
down_revision = 'a209c1a3f8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwrd', sa.String(length=25), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.drop_column('users', 'passwrd')
    # ### end Alembic commands ###
